[versions]
minecraft = "1.21.1"
fabric-loader = "0.16.5"
fabric-api = "0.105.0+1.21.1"
mappings-yalmm = "2"
mappings-parchment = "2024.07.28"

# Dependencies
yumi-commons = "1.0.0-alpha.1"
spruceui = "5.1.0+neo-t0+1.21.1"
pridelib = "1.2.1+neo-t2+1.21.1"
modmenu = "11.0.1"
trinkets = "3.10.0"
accessories = "1.1.0-beta.16+1.21.1"
sodium = "mc1.21-0.5.9"

# Configuration
nightconfig = "3.8.1"

# Gradle
gradle-licenser = "2.0.+"
gradle-loom = "1.7.+"
mappingio = "0.6.1"

neoforge = "21.1.66"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
# Dependencies
yumi-commons-core = { module = "dev.yumi.commons:yumi-commons-core", version.ref = "yumi-commons" }
yumi-commons-collections = { module = "dev.yumi.commons:yumi-commons-collections", version.ref = "yumi-commons" }
yumi-commons-event = { module = "dev.yumi.commons:yumi-commons-event", version.ref = "yumi-commons" }
spruceui = { module = "dev.lambdaurora:spruceui", version.ref = "spruceui" }
pridelib = { module = "io.github.queerbric:pridelib", version.ref = "pridelib" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
trinkets = { module = "dev.emi:trinkets", version.ref = "trinkets" }
accessories = { module = "io.wispforest:accessories-fabric", version.ref = "accessories" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

# Configuration
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "nightconfig" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "nightconfig" }

# Gradle
gradle-licenser = { module = "dev.yumi:yumi-gradle-licenser", version.ref = "gradle-licenser" }
gradle-loom = { module = "dev.architectury:architectury-loom", version.ref = "gradle-loom" }
mappingio = { module = "net.fabricmc:mapping-io", version.ref = "mappingio" }